### ISSUE TITLE
Hide Scrollbar

### ISSUE THREAD

**Issue by AyanavaKarmakar** [AyanavaKarmakar/ELFIN#1]
~~https://github.com/reslear/tailwind-scrollbar-hide~~

**Comment by AyanavaKarmakar** [comment]
```css
::-webkit-scrollbar {
    display: none;
}
```
